MovieCloud_project/MovieCloud_project/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from Movies.views import HomeView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view()),
    path('movies/', include('Movies.urls',namespace='movies')),
]

urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

MovieCloud_project/Movies/urls.py
from django.contrib import admin
from django.urls import path
from .views import MovieList,MovieDetail,MovieCategory,MovieLanguage,MovieSearch,MovieYear

app_name='movies'

urlpatterns = [
    path('', MovieList.as_view(),name='movie_list'),
    path('category/<str:category>/', MovieCategory.as_view(),name='movie_category'),
    path('language/<str:lang>/', MovieLanguage.as_view(),name='movie_language'),
    path('search/', MovieSearch.as_view(),name='movie_search'),
    path('<slug:slug>/', MovieDetail.as_view(),name='movie_detail'),
    path('year/<int:year>/', MovieYear.as_view(),name='movie_year'),
]

MovieCloud_project/Movies/models.py
from django.db import models
from django.utils.text import slugify
from django.utils import timezone
# Create your models here.

CATEGORY_CHOICE=(
    ('action','ACTION'),
    ('drama','DRAMA'),
    ('romance','ROMANCE'),
    ('comedy','COMEDY'),
)

LANGUAGE_CHOICE=(
    ('hindi','HINDI'),
    ('english','ENGLISH'),

)

STATUS_CHOICE=(
    ('RA','RECENTLY ADDED'),
    ('MW','MOST WATCHED'),
    ('TR','TOP RATED'),
)

class Movie(models.Model):
    title=models.CharField(max_length=100)
    discription=models.TextField(max_length=1000)
    image=models.ImageField(upload_to='Movies')
    banner=models.ImageField(upload_to='Movies_banner')
    category=models.CharField(choices=CATEGORY_CHOICE,max_length=12)
    language=models.CharField(choices=LANGUAGE_CHOICE,max_length=10)
    status=models.CharField(choices=STATUS_CHOICE,max_length=2)
    cast=models.CharField(max_length=100)
    year_of_prod=models.DateField()
    views_count=models.IntegerField(default=0)
    movie_trailer=models.URLField()
    created=models.DateTimeField(default=timezone.now)
    
    

    slug=models.SlugField(blank=True,null=True)

    def save(self,*args,**kwargs):
        if not self.slug:
            self.slug=slugify(self.title)
        super(Movie,self).save(*args,**kwargs)

    def __str__(self):
        return self.title



LINK_CHOICES=(
    ('D','Download'),
    ('W','Watch'),
    
)

class watch_links(models.Model):
    movie=models.ForeignKey(Movie,related_name="movie_watch_link",on_delete=models.CASCADE)
    type=models.CharField(choices=LINK_CHOICES,max_length=1)
    link=models.URLField()

    def __str__(self):
        return str(self.movie)

# class download_links(models.Model):
#     movie=models.ForeignKey(Movie,related_name="movie_watch_link",on_delete=models.CASCADE)
#     link=models.URLField()

MovieCloud_project/Movies/views.py
from unicodedata import category
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from django.views.generic.dates import YearArchiveView
from Movies.models import Movie,watch_links
from datetime import date
# Create your views here.

class HomeView(ListView):
    model=Movie
    template_name='Movies/home.html'
    
    def get_context_data(self, **kwargs):
        context=super(HomeView,self).get_context_data(**kwargs)
        context['top_rated']=Movie.objects.filter(status='TR')
        context['most_watched']=Movie.objects.filter(status='MW')
        context['recently_added']=Movie.objects.filter(status='RA')
        print(context)
        return context


class MovieList(ListView):
    model=Movie
    paginate_by=1
    #context_object_name: ''
    #template_name: 'movie_list.html'


class MovieDetail(DetailView):
    model=Movie
    
    def get_object(self):
        object=super(MovieDetail,self).get_object()
        object.views_count += 1
        object.save()
        return object

    def get_context_data(self, **kwargs):
        context=super(MovieDetail,self).get_context_data(**kwargs)
        context['links']=watch_links.objects.filter(movie=self.get_object())
        context['related_movies']=Movie.objects.filter(category=self.get_object().category)#.order_by('created')[0:6]
        print(context)
        return context


class MovieCategory(ListView):
    model=Movie
    paginate_by=2
    
    def get_queryset(self):
        self.category=self.kwargs['category']
        return Movie.objects.filter(category=self.category)

    def get_context_data(self, **kwargs):
        context=super(MovieCategory,self).get_context_data(**kwargs)
        context['movie_category']=self.category
        
        return context


class MovieLanguage(ListView):
    model=Movie
    paginate_by=2
    
    def get_queryset(self):
        self.language=self.kwargs['lang']
        return Movie.objects.filter(language=self.language)

    def get_context_data(self, **kwargs):
        context=super(MovieLanguage,self).get_context_data(**kwargs)
        context['movie_language']=self.language
        
        return context


class MovieSearch(ListView):
    model=Movie
    paginate_by=1
    
    def get_queryset(self):
        query=self.request.GET.get('query')
        if query:
            object_list=self.model.objects.filter(title__icontains=query)
            print(query)
            print(object_list)
        else:
            object_list=self.model.objects.none()
        return object_list

class MovieYear(YearArchiveView):
    model=Movie
    queryset=Movie.objects.all()
    date_field='year_of_prod'
    make_object_list=True
    allow_future=True
    print(queryset)
    print(date_field)

MovieCloud_project/templates/Movies/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Movies</title>
        <meta name="viewport" content="width=device-width", initial-scale="1", minimum-scale="1" maximum-scale="1">
        <!--Link Swiper's css-->
        <link rel="stylesheet" href="{%static 'css/swiper.min.css' %}">
        <link rel="stylesheet" href="{%static 'css/style.css' %}">

        <script src="{%static 'js/jquery-3.1.1.min.js' %}"></script>
        <script src="{% static 'js/script.js' %}"></script>
        <style>
            body{
                background-color:silver;
                
            }
        </style>
    </head>
    <body>
        <div class="wrapper">
            <header class="header">
                <figure class="logo"><a href="index.html"><img src="img/logo.png" alt="Logo"></figure></a>
                <nav class="Menu">
                    <ul>
                        <li><a href=index.html>Home</a></li>
                        <li><a>Geners</a>
                            <ul>
                                <li><a href="{% url 'movies:movie_category' 'action' %}">Action</a></li>
                                <li><a href="{% url 'movies:movie_category' 'comedy' %}">Comedy</a></li>
                                <li><a href="{% url 'movies:movie_category' 'drama' %}">Drama</a></li>
                                <li><a href="{% url 'movies:movie_category' 'romance' %}">Romance</a></li>
                            </ul>
                        </li>
                        <li><a>Year</a>
                        <ul>
                            <li><a href="{% url 'movies:movie_year' year=2017 %}">2017</a></li>
                            <li><a href="{% url 'movies:movie_year' year=2016 %}">2016</a></li>
                            <li><a href="{% url 'movies:movie_year' year=2015 %}">2015</a></li>
                            <li><a href="{% url 'movies:movie_year' year=2014 %}">2014</a></li>
                        </ul></li>
                        <li><a>Language</a>
                        <ul>
                            <li><a href="{% url 'movies:movie_language' 'hindi' %}">Hindi</a></li>
                            <li><a href="{% url 'movies:movie_language' 'english' %}">English</a></li>
                        </ul>
                        </li>
                        <!--li><a href="mostwatched.html">Most Watched</a></li-->
                        <li class="mobsearch">
                            <form class="mobform" >
                                <input type="text" name="query"  class="mobsearchfield" placeholder="Search..">
                                <input type="submit" value="" class="mobsearchsubmit">

                            </form></li>
                        </ul>
                </nav>
                <form class="search" mathod="GET" action="{% url 'movies:movie_search'%}">
                    <input type="text" name="query" value="{{request.GET.query}}" class="searchfield" placeholder="Search...">
                    <input type="submit" value="" class="Searchsubmit">

                </form>
                <div class="toggle"><img src="img/menu.svg"></div>
            </header>
            <!--Swiper-->
            <div class="homeslider">
                <div class="swiper-container">

                    <div class="swiper-wrapper">
                        
                            <div class="swiper-slide">
                                {% if slider_movie.banner %}
                                    <img src="{{slider_movie.banner.url}}">
                                {% endif %}
                                <div class="caption">
                                    <div class="captioninside">
                                        <h3>{{slider_movie.title}}</h3>
                                        <p>{{slider_movie.discription}}</p>
                                        <a href="{% url 'movies:movie_detail' slider_movie.slug %}" class="playbutton">play</a>
                                    </div>
                                </div>
                            </div>
                       
                        <!---div class="swiper-slide">
                            <img src="images/slider/poster1.jpg">
                            <div class="caption">
                                <div class="captioninside">
                                    <h3>Movie Title2</h3>
                                    <p>Movie Name</p>
                                    <a href="single.html" class="playbutton">play</a>
                                </div>
                            </div>
                        </div>
                        <div class="swiper-slide">
                            <img src="images/slider/poster3.jpg">
                            <div class="caption">
                                <div class="captioninside">
                                    <h3>Movie Title 3</h3>
                                    <p>Movie Name</p>
                                    <a href="single.html" class="playbutton">play</a>
                                </div>
                            </div>
                        </div--->
                    </div>
                    <!--Add Paginatin-->
                    <div class="swiper-pagination"></div>
                </div>
            </div>
            {% block body_block %}

            {% endblock %}
            <footer class="footer">
                <div class="copyright"><p>Copyright & copy 2017 www.abcd.com</p></div>
                <div class="footermenu">
                    <ul>
                        <li><a href="index.html">Home</a></li>
                        <li><a href="contact.html">Contact</a></li>
                        <li><a href="terms.html">terms & conditions</a></li>

                    </ul>
                </div>
                <div class="tags">
                    <ul>
                        <li>Watch Free Movies Trailer</li>
                        <li>Movie Trailers</li>
                        <li>English subtitled movie Trailer</li>
                        <li>Latest movie Trailer</li>
                        <li>New movie Trailer</li>
                    </ul>
                </div>

            </footer>







        </div>



















    </body>































    </html>

MovieCloud_project/templates/Movies/home.html
{% extends 'Movies/base.html' %}
{% load static %}
{% block body_block %}
<main class="content">
    <section class="panel">
        <h2>Recently Added</h2>
        <div class="recentslider">
            <div class="swiper-container">
                <div class="swiper-wrapper">
                    {% for movie in recently_added  %}
                        <div class="swiperide"><a href="single.html"><img src="{{movie.image.url}}"><h3 class="hometitle">{{movie.title}}</h3></a></div>
                    {% endfor %}
                    <!---div class="swiper-slide"><a href="single.html"><img src="image/8.jpg"><h3 class="movietitle"></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/7.jpg"><h3 class="movietitle"></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/5.jpg"><h3 class="movietitle"></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/4.jpg"><h3 class="movietitle"></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class="movietitle"></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class="movietitle"></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class="movietitle"></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class="movietitle"></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div---->

                    <div class="swiper-slide"><a href="mostwatched.html"><img src="img/others.png"></a></div>
                </div>
                <div class="nextdirection recent-next"><img src="{% static 'images/rightarrow2' %}"></div>
                <div class="leftdirection recent-prev"><img src="{% static 'images/leftarrow' %}"></div>
            </div>
        </div>
    </section>
    <section class="panel">
        <h2>Most Watched</h2>
        <div class="recentslider">
            <div class="swiper-container">
                <div class="swiper-wrapper">
                    {% for movie in most_watched  %}
                        <div class="swiper-slide"><a href="single.html"><img src="{{movie.image.url}}"><h3 class="hometitle">{{movie.title}}</h3></a></div>
                    {% endfor %}
                    <!----div class="swiper-slide"><a href="single.html"><img src="image/8.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/7.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/5.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/4.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div---->
                    
                    <div class="swiper-slide"><a href="mostwatched.html"><img src="img/others.png"></a></div>
                </div>
                <div class="nextdirection most-next"><img src="{% static 'images/rightarrow2' %}"></div>
                <div class="leftdirection most-prev"><img src="{% static 'images/leftarrow' %}"></div>
                <!---Add Pagination-->
            </div>
        </div>
    </section>
    <section class="panel">
        <h2>Top Rated</h2>
        <div class="recentslider">
            <div class="swiper-container">
                <div class="swiper-wrapper">
                    {% for movie in top_rated  %}
                    <div class="swiper-slide"><a href="single.html"><img src="{{movie.image.url}}"><h3 class="hometitle">{{movie.title}}</h3></a></div>

                    {% endfor %}
                    
                    <!----div class="swiper-slide"><a href="single.html"><img src="image/8.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/7.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/5.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/4.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div---->
                    
                    <div class="swiper-slide"><a href="mostwatched.html"><img src="img/others.png"></a></div>
                </div>
                <div class="nextdirection top-next"><img src="{% static 'images/rightarrow2' %}"></div>
                <div class="leftdirection top-prev"><img src="{% static 'images/leftarrow' %}"></div>
                <!---Add Pagination-->
            </div>
        </div>
    </section>
</main>



{% endblock %}

MovieCloud_project/templates/Movies/movie_detail.html
{% extends 'Movies/base.html' %}
{% block body_block %}
    <main class="content">
        <div class="single">
            <section class="trailer">
                <h3>Trailer</h3>
                <div class="trailer-frame">
                    <iframe width="560" height="315" src="{{object.movie_trailer}}" frameborder="0" allowfullscreen></iframe>
                </div>
            </section>

            <section class="movie">
                <img src="{{object.image.url}}">
                <ul>
                    <li>{{object}}</li>
                    <li>{{object.description}}</li>
                    <li><a href="genre.html">Adventure</a>, <a href="genre.html">Drame</a>, <a href="genre.html">Romance</a>, <a href="genre.html">Comedy</a></li>
                    <li><a href="">{{object.cast}}</a></li>
                    <li>{{object.views_count}} Views</li>
                </ul>
            </section>
            <section class="links">
                <h3>Links</h3>
                <ul class="links">
                    <li><a>Download</a></li>
                    {% for link in links %}
                        {% if link.type == 'D' %}
                            <li><a href="{{link1.link}}">Link{{forloop.counter}}</a></li>
                        {% endif %}
                    {% endfor %}
                    <!--li><a href="#">Link2</a></li>
                    <li><a href="#">Link3</a></li-->
                </ul>
                <ul class="wlinks">
                    <li><a>Watch</a></li>
                    {% for link in links %}
                        {% if link.type == 'W' %}
                            <li><a href="{{link1.link}}">Link{{forloop.counter}}</a></li>
                        {% endif %}
                    {% endfor %}
                    <!--li><a href="#">Link2</a></li>
                    <li><a href="#">Link3</a></li-->
                </ul>
            </section>

            <section class="related">
                <h3>Related Movies</h3>
                {% for movie in related_movies %}
                    <div class="relatemovie">
                        <a href="{% url 'movies:movie_detail' movie.slug %}"><img src="{{movie.image.url}}"></a>
                        <a href="{% url 'movies:movie_detail' movie.slug %}"><span class="relatename">{{movie.title}}</span></a>
                    </div>
                {% endfor %}
                
                <!-----div class="relatemovie">
                    <a href="#"><img src="image/4.jpg"></a>
                    <a href="#"><span class="relatename">Name of movie</span></a>
                </div>
                <div class="relatemovie">
                    <a href="#"><img src="image/4.jpg"></a>
                    <a href="#"><span class="relatename">Name of movie</span></a>
                </div>
                <div class="relatemovie">
                    <a href="#"><img src="image/4.jpg"></a>
                    <a href="#"><span class="relatename">Name of movie</span></a>
                </div>
                <div class="relatemovie">
                    <a href="#"><img src="image/4.jpg"></a>
                    <a href="#"><span class="relatename">Name of movie</span></a>
                </div>
                <div class="relatemovie">
                    <a href="#"><img src="image/4.jpg"></a>
                    <a href="#"><span class="relatename">Name of movie</span></a>
                </div---->
            
            </section>

            <!--section class="comments">
                <h3>Comments</h3>
            </section-->
        </div>
    </main>
{% endblock %}

MovieCloud_project/templates/Movies/movie_list.html
<!DOCTYPE html>
{% extends 'Movies/base.html' %}
{% block body_block %}
    <main class="content">
        <section class="centered">
            {% if movie_category %}
                <h3>{{movie_category|title}} Movies</h3>
            {% endif %}

            {% if movie_language %}
                <h3>{{movie_language|title}} Movies</h3>
            {% endif %}
            <div class="movies">
                {% for movie in object_list %}
                <div class="mov">
                    <a href="{% url 'movies:movie_detail' movie.slug %}">
                        <img src="{{movie.image.url}}">
                        <h3 class="movietitle">{{movie.title}}</h3>
                    </a>
                </div>
                {% empty %}
                    <h3>There are no movies in this category.</h3>
                {% endfor %}
            </div>
<!---  <section class="panel">
        <h2>Recently Added</h2>
        <div class="recentslider">
            <div class="swiper-container">
                <div class="swiper-w-slrapper">
                    <div class="swiperide"><a href="single.html"><img src="image/9.jpg"><h3 class="movietitle">Bahubali</h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/8.jpg"><h3 class="movietitle">RRR</h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/7.jpg"><h3 class="movietitle">sooryavanshi</h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/5.jpg"><h3 class="movietitle"></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/4.jpg"><h3 class="movietitle"></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class="movietitle"></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class="movietitle"></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class="movietitle"></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class="movietitle"></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="mostwatched.html"><img src="img/others.png"></a></div>
                </div>
                <div class="nextdirection most-next"><img src="img/right-arrow.svg"></div>
                <div class="leftdirection most-prev"><img src="img/left-arrow.svg"></div>
            </div>
        </div>
    </section>
    <section class="panel">
        <h2>Most Watched</h2>
        <div class="recentslider">
            <div class="swiper-container">
                <div class="swiper-wrapper">
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/8.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/7.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/5.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/4.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                </div>
            </div>
        </div>
    </section>
    <section class="panel">
        <h2>Top Rated</h2>
        <div class="recentslider">
            <div class="swiper-container">
                <div class="swiper-wrapper">
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/8.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/7.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/5.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/4.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                    <div class="swiper-slide"><a href="single.html"><img src="image/9.jpg"><h3 class=></h3></a></div>
                </div>
            </div>
        </div>-->
        {% if is_paginated %}
        <nav class="pagination">
            <ul>
                {% if page_obj.has_previous %}
                    <li><a href="?page={{page_obj.previous_page_number}}">Prev</a></li>
                {% else %}
                    <li class="disabled"></li>
                {% endif %}


                {% for pages in page_obj.paginator.page_range %}
                 {% if page_obj.number == pages %}
                    <li><a href="#">{{pages}}</a></li>
                 {% else %}
                    <li><a href="?page={{pages}}">{{pages}}</a></li>
                 {% endif %}
                {% endfor %}


                {% if page_obj.has_next %}
                    <li><a href="?page={{page_obj.next_page_number}}">Next</a></li>
                {% else %}
                    <li class="disabled"></li>
                {% endif %}
                
            </ul>
        </nav>
        {% endif %}
    </section>
</main>
{% endblock %}





<!----<li><a href="#" class="menuactive">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">...</a></li>
                <li><a href="#">20</a></li>
                <li><a href="#">21</a></li>----->